export const products = {
  café: {
    lunch: [
      {
        id: 1,
        title: "Crab Eggs",
        category: "Lunch",
        description: "",
        price: "300",
        image: "/image/product/CrabEggs.png",
      },
      {
        id: 2,
        title: "Clarifying Balls",
        category: "Lunch",
        description: "",
        price: "250",
        image: "/image/product/ClarifyingBalls.png",
      },
      {
        id: 3,
        title: "Holy Excrement",
        category: "Lunch",
        description: "",
        price: "100",
        image: "/image/product/HolyExcrement.png",
      },
      {
        id: 4,
        title: "Redflesh Mushrooms",
        category: "Lunch",
        description: "",
        price: "250",
        image: "/image/product/RedfleshMushrooms.png",
      },
      {
        id: 5,
        title: "Moldy Leftovers",
        category: "Lunch",
        description: "",
        price: "10",
        image: "/image/product/MoldyLeftovers.png",
      },
    ],
    dinner: [
      {
        id: 1,
        title: "Exalted Flesh",
        category: "Dinner",
        description: "",
        price: "450",
        image: "/image/product/ExaltedFlesh.png",
      },
      {
        id: 2,
        title: "Beast Liver",
        category: "Dinner",
        description: "",
        price: "900",
        image: "/image/product/BeastLiver.png",
      },
      {
        id: 3,
        title: "Innard Meat",
        category: "Dinner",
        description: "",
        price: "100",
        image: "/image/product/InnardMeat.png",
      },
      {
        id: 4,
        title: "Octopus Ovary",
        category: "Dinner",
        description: "",
        price: "1 500",
        image: "/image/product/OctopusOvary.png",
      },
      {
        id: 5,
        title: "Turtle Neck",
        category: "Dinner",
        description: "",
        price: "750",
        image: "/image/product/TurtleNeck.png",
      },
    ],
    dessert: [
      {
        id: 1,
        title: "Moonlight Cake",
        category: "Dessert",
        description: "",
        price: "500",
        image: "/image/product/MoonlightCake.png",
      },
      {
        id: 2,
        title: "Shabriri Grapes",
        category: "Dessert",
        description: "",
        price: "1 000",
        image: "/image/product/ShabririGrapes.png",
      },
      {
        id: 3,
        title: "Beast Eye",
        category: "Dessert",
        description: "",
        price: "600",
        image: "/image/product/BeastEye.png",
      },
      {
        id: 4,
        title: "Golden Seeds",
        category: "Dessert",
        description: "",
        price: "10 000",
        image: "/image/product/GoldenSeeds.png",
      },
    ],
    drinks: [
      {
        id: 1,
        title: "Holy Water",
        category: "Drinks",
        description: "",
        price: "200",
        image: "/image/product/HolyWater.png",
      },
      {
        id: 2,
        title: "Crimson Tears",
        category: "Drinks",
        description: "",
        price: "300",
        image: "/image/product/CrimsonTears.png",
      },
      {
        id: 3,
        title: "Cerulean Tears",
        category: "Drinks",
        description: "",
        price: "300",
        image: "/image/product/CeruleanTears.png",
      },
      {
        id: 4,
        title: "Marika's Blessing",
        category: "Drinks",
        description: "",
        price: "10 000",
        image: "/image/product/MarikasBlessing.png",
      },
      {
        id: 5,
        title: "Wondrous Alcohol",
        category: "Drinks",
        description: "",
        price: "500",
        image: "/image/product/WondrousAlcohol.png",
      },
    ],
  },
  attire: {
    head: [
      {
        id: 0,
        title: "",
        category: "",
        description: "",
        price: "",
        image: "/image/product/.png",
      },
    ],
  },
  armaments: {
    daggers: [
      {
        id: 0,
        title: "",
        category: "",
        description: "",
        price: "",
        image: "/image/product/.png",
      },
    ],
  },
};
